# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gitramy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Kingfisher', '~> 7.0'
pod 'SwiftSVG', '~> 2.0'
pod 'Charts'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
  # Pods for Gitramy

end
